[run]
    concurrency = 4
    tests = false

[[issues.exclude-rules]]
    linters = ["misspell"]
    source = "cancelled"

[linters-settings]
    [linters-settings.gocognit]
        min-complexity = 12

    [linters-settings.gofumpt]
        lang-version = "1.20"
        extra-rules = true

    [linters-settings.goconst]
        min-len = 2
        min-occurrences = 2

    [linters-settings.misspell]
        locale = "US"

    [linters-settings.errcheck]
        ignore = "fmt:.*,github.com/go-kit/kit/log:^Log$"

    [linters-settings.exhaustive]
        default-signifies-exhaustive = true

[linters]

    # Allow-listing, to be more CI safe.
    disable-all = true

    # @see https://golangci-lint.run/usage/linters/#enabled-by-default-linters
    enable = [
        "staticcheck",
        "gosimple",
        "ineffassign",
        "typecheck",
        "govet",
        "errcheck",
        "unused",
        "exhaustive",
        "stylecheck",
        "gosec",
        "unconvert",
        "goconst",
        "depguard",
        "misspell",
        "unparam",
        "prealloc",
        "gofumpt",
        "exportloopref",
        "gocritic",
    ]
