version = '2'

[run]
concurrency = 4
tests = false

[linters]
default = 'none'
enable = [
  'errcheck',
  'exhaustive',
  'goconst',
  'gocritic',
  'gosec',
  'govet',
  'ineffassign',
  'misspell',
  'prealloc',
  'staticcheck',
  'unconvert',
  'unparam',
  'unused'
]

[linters.settings]
[linters.settings.exhaustive]
default-signifies-exhaustive = true

[linters.settings.gocognit]
min-complexity = 12

[linters.settings.goconst]
min-len = 3
min-occurrences = 2

[linters.settings.misspell]
locale = 'US'

[linters.exclusions]
generated = 'lax'
presets = [
  'comments',
  'common-false-positives',
  'legacy',
  'std-error-handling'
]
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[[linters.exclusions.rules]]
linters = [
  'misspell'
]
source = 'cancelled'

[formatters]
enable = [
  'gofumpt'
]

[formatters.settings]
[formatters.settings.gofumpt]
extra-rules = true

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]
