#!/usr/bin/env bash

set -o pipefail -o nounset -o errexit -o errtrace

ROOT_DIR="$(pwd)"
while [ ! -d "${ROOT_DIR}/.git" ]; do

    ROOT_DIR="$(dirname ${ROOT_DIR})"
    if [ "x${ROOT_DIR}" == "x/" ]; then
        echo "Cannot find .git directory, I use that as reference for the commands."
        exit 1
    fi
done

echo "Running the checks in ${ROOT_DIR}..."
go build ./... && \
    golangci-lint run

go test -short ./...

cp go.mod go.mod.bak
cp go.sum go.sum.bak
tidy=$(go mod tidy -v 2>&1)
if [[ "$tidy" != "" ]]; then
    mv go.mod.bak go.mod
    mv go.sum.bak go.sum

    echo "go mod tidy:"
    echo $tidy
    exit 1
fi

rm go.mod.bak
rm go.sum.bak

go mod verify
