# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  lint-and-test:
    working_directory: /home/circleci/eri
    docker:
      # specify the version
      - image: circleci/golang:1.17

    environment:
        BINARY_NAME: "eri-linux-amd64"
        TEST_RESULTS: "/tmp/test-results"

    steps:
      - checkout
      - run: mkdir -p ${TEST_RESULTS}
      - run: go install github.com/jstemmer/go-junit-report@latest
      - run: go install github.com/mattn/goveralls@latest
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0

      - run:
          name: Build
          command: |
            TAG=${CIRCLE_TAG:-dev}
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o "${BINARY_NAME}" -a -ldflags="-w -s -X main.Version=${TAG}" ./cmd/web

      - run:
          # Check if we have updates to minor/patch level packages we're explicitly referencing
          name: Dep check
          command: |
            go list -u -f '{{if (and (not (or .Main .Indirect)) .Update)}}{{.Path}}: {{.Version}} -> {{.Update.Version}}{{end}}' -m all 2> /dev/null

      - run:
          name: Lint
          command: |
            golangci-lint run

      - run:
          name: Test
          command: |
            go test -v ./... | go-junit-report > ${TEST_RESULTS}/report.xml
            go test -cover -race -covermode=atomic -coverprofile=${TEST_RESULTS}/coverage.txt ./...
            go tool cover -html=${TEST_RESULTS}/coverage.txt -o ${TEST_RESULTS}/coverage.html

      - store_test_results:
          path: "/tmp/test-results"

      - store_artifacts:
          path: "/tmp/test-results"

      - run:
          name: Coveralls upload
          command: |
            goveralls -coverprofile=${TEST_RESULTS}/coverage.txt -service=circle-ci -repotoken=${COVERALLS_TOKEN}


workflows:
  version: 2
  build-test:
    jobs:
      - lint-and-test:
          context:
            - org-global
            - "Public repos"
          filters:
            branches:
              only: /.*/
